# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-11 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (0, '女')], default=1, verbose_name='性别'),
        ),
    ]
