# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-09 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_book_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comment_num',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='book',
            name='keep_num',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
    ]
