# tu = (11,2,True,[2,3,4],'alex')
# for i in tu:
#     print(i)
# print(tu[1])
# print(tu[:3:2])
# print(tu.index(True))
# print(tu.count(2))
# print(len(tu))
# tu[-2].append(666)
# print(tu)