# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20180827_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.IntegerField(null=True, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='author',
            name='create_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='sex',
            field=models.SmallIntegerField(choices=[(0, '女'), (1, '男'), (2, '保密')], default=2, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='book',
            name='create_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='create_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='app01.Author', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=36, unique=True, verbose_name='图书'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app01.Publisher', verbose_name='出版社'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=36, unique=True, verbose_name='出版社'),
        ),
    ]
