# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        ('repository', '0006_auto_20181108_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='roles',
            field=models.ManyToManyField(to='rbac.Role', verbose_name='关联角色'),
        ),
        migrations.AlterField(
            model_name='admininfo',
            name='password',
            field=models.CharField(max_length=64, verbose_name='密码'),
        ),
    ]
