# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-14 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_auto_20181113_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
    ]
