# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_remove_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='latest_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='上次采集时间'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='手机号'),
        ),
    ]
