#!/usr/bin/env python3
# # a = 3
# # print(a.bit_length())
#
# s = "  python自动化21期   "
# print(s[0])
# print(s[-1])
# print(s[:6])
# print(s[:6:2])
# print(s[-1:-5:-1])
# print(s.capitalize())
# print(s.center(20, "-"))
# print(s.count("p", 0, 2))
# print(s.encode("utf-8"))
# print(s.find("1"))
# print(s.startswith("p"))
# print(s.startswith("x"))
# print(s.endswith("x"))
# print(s.endswith("期"))
# print("{0}{0}{1}".format(2, 3))
# print(s.index("1"))
# print(len(s))
# print(s.count("s"))
# print(s.isalnum())
# print(s.isalpha())
# print(s.isdigit())
# print("_".join(s))
# print(s.ljust(20, "a"))
# print(s.upper())
# print(s.strip())
# print(s.lstrip())
# print(s.rstrip())
# print(s.replace("p", "AAA"))
# print(s.split("h"))
# print(s.swapcase())
# print(bool(1))
# print(int(True))
# print(int(False))
# print(bool(""))
# print(bool("3"))
# l = []
# l.append("3")
# l.append([1, 2, 3])
# l.insert(0, "a")
# l.extend((1, 2, 3))
# l.pop(0)
# l.remove(2)
# print(l)
# d1 = dict.fromkeys("abc", [])
# print(d1)
# d1["a"].append(1)
# print(d1)
#
# l = [1, 2, 3, 3, 4, 5, 6, 3, 2, 3, 4]
# s = set(l)
# print(s)
# s.add("3233")
# s.update("abc")
# print(s)
a = [1,2,3]
b = a
a.append(333)
print(a, b)
