# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-02 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fault_reporting', '0004_auto_20180902_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faultreport',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
    ]
