# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fault_reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='评论总数'),
        ),
        migrations.AlterField(
            model_name='fault',
            name='down_count',
            field=models.IntegerField(default=0, verbose_name='反正总数'),
        ),
        migrations.AlterField(
            model_name='fault',
            name='summary',
            field=models.TextField(max_length=100, verbose_name='故障概述'),
        ),
        migrations.AlterField(
            model_name='fault',
            name='up_count',
            field=models.IntegerField(default=0, verbose_name='点赞总数'),
        ),
    ]
