# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fault_reporting', '0003_auto_20180904_1724'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fault2tag',
            unique_together=set([('fault', 'tag')]),
        ),
    ]
