# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-02 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_dept_employee2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alex', models.DateTimeField()),
            ],
        ),
    ]
