# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fault_reporting', '0004_auto_20180904_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faultdetail',
            name='fault',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fault_reporting.Fault', verbose_name='故障总结'),
        ),
    ]
