# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-12 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='alex', max_length=12),
        ),
    ]
