# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-26 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': '出版社', 'verbose_name_plural': '出版社'},
        ),
        migrations.AddField(
            model_name='book',
            name='phone',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.TextField(verbose_name='出版社地址'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='出版社名称'),
        ),
    ]
