# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-07 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20181105_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='latest_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次采集时间'),
        ),
        migrations.AddField(
            model_name='server',
            name='server_status_id',
            field=models.IntegerField(choices=[(1, '上架'), (2, '在线'), (3, '离线'), (4, '下架')], default=1),
        ),
    ]
