# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-06 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180806_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=64),
        ),
    ]
