#!/usr/bin/env python3
# 1. 字符编码的发展背景，历程做简要概述
# 二进制  十进制  ascii (gbk等其等其他国家编码) unicode  utf-8
# 2. python运算符有哪些？每种运算符下有哪些方法？
# 数学运算：+ - * / %
# 比较运算：> < == >= <=  !=
# 逻辑运算  and  or  not
# 3. python的数据类型有哪些？每种数据类型的特征？
# str 字符串
# int 数字类型
# float 浮点类型
# 列表
# 元组（不可变列表）
# 字典
# 集合
# 4. 列举字符串的10种常用方法
# s = "5  AbcA123 45"
# s1 = s.replace("A", "a")  # 默认替换所有
# print(s1)
# s2 = s.replace("A", "a", 1)  # 只替换第一个
# print(s2)
# s3 = s.strip() # 默认去掉空格
# print(s3)
# s4 = s.strip("45") #
# print(s4)
# print(s.index("A"))  # 通过元素取索引
# s = "abc#def^gh"
# print(s.title())
# s = "aBcDeF"
# print(s.swapcase())
# 5. 列举列表的10种常用方法
# 6. 已知字符串 name = “aahhh113244ADD.,/'[@#$hhhhTTTTTT666”,要求如下:
# 	1.请将name字符串的数字取出，并输出成一个新的字符串。
# 	2.请去除name字符串多次出现的字母，仅留最先出现的一个。例 ‘abcabb’，经过去除后，输出 ‘abc’
# 	3.请将name字符串反转并输出。例：’abc’的反转是’cba’
# name = "aahhh113244ADD., / '[@#$hhhhTTTTTT666"
# # name2 = "".join([i for i in name if i.isdigit()])
# # print(name2)
# lst = list(name)
# lst.reverse()
# print("".join(lst))

# name1 = "".join(lst)
# print(name1)
# 7. 8<<2等于？
# print(8 << 2)
# 8. s=[1,"h",2,"e",[1,2,3],"l",(4,5),"l",{1:"111"},"o"],将s中的5个字符提取出来并拼接成字符串。
# s=[1,"h",2,"e",[1,2,3],"l",(4,5),"l",{1:"111"},"o"]
# s1 = "".join([i for i in s if str(i).isalpha()])
# print(s1)
# 9.
# a = [1,2,[3,"hello"],{"egon":"aigan"}]
# b = a[:]
# c = a
#
# a[0] = 5  # [5,2,[3,"hello"],{"egon":"aigan"}]
# a[2][0] = 666 # [5,2,[666,"hello"],{"egon":"aigan"}]
# #
# print(a)  # [5,2,[666,"hello"],{"egon":"aigan"}]   正常修改后的结果
# print(b)  # [1,2,[666,"hello"],{"egon":"aigan"}]   b 等于 a的值并不是等于a,所以索引0不会变，但列表里面的列表又共享内存地址所以会跟着变
# print(c)  # [5,2,[666,"hello"],{"egon":"aigan"}]   c 等于 a 所以c和a共享内存地址，所有c会随着a进行变化
# # 	#计算结果以及为什么？
# # 10.
# list1 = [2, 3, 8, 4, 9, 5, 6]
# list2 = [5, 6, 10, 17, 11, 2]
# # 	升序合并并去重在 list3 列表中
# print(set(list1) | set(list2))  # 并集
# print(set(list1) & set(list2))  # 交集
# print(set(list1) ^ set(list2))  # 反交集
# print(set(list1) - set(list2))  # 差集
# print(set(list1) < set(list2))  # 子集
# print(set(list1) > set(list2))  # 超集

# 11. 用至少2种不同的方式删除一个list里面的重复元素
# lst = [6,1,1,2,3,4,5,6,6,5]
# lst1 = set(lst)
# print(lst1)
# count = 0
# 10. 通过函数化编程实现5的阶乘
# 5*4*3*2*1
# def func(argv):
#     if argv == 1:return 1
#     return func(argv-1) * argv
# print(func(5))
# 11. 编写代码实现9*9乘法口诀表
# 	1 * 1 = 1
# 	2 * 1 = 2   2 * 2 = 4
# 	3 * 1 = 3   3 * 2 = 6   3 * 3 = 9
# for i in range(1, 10):
#     for x in range(1, i + 1):
#         print("%s * %s = %s" % (x, i, i * x), end=" ")
#     print()

# for i in range(1, 10):
#     for j in range(1, i+1):
#         print('%s * %s = %2s' % (j, i, i*j), end=' ')
#     print()
# # 12. 输入一个年份，判断是否是闰年？
# def func(argv):
#     if argv % 4 == 0 and argv % 100 != 0:
#         return "闰年"
#     else:
#         return "平年"
#
# print(func(1900))
# # 13. 任意输入三个数，判断大小？
# def func(x, y, z):
#     return max(x, y, z)
# print(func(5,7,9))
# 14. 写三层循环，用户在最里层退出，整个程序终止。


# 15. a = 12，b = 13，不用中间变量交换a和b的值？
# a = 12
# b = 13
# a, b = b, a
# print(a, b)
# 16.
# def f(x, l = [] ): # x = 2    # x =  3  l = [3,2,1]
#     for i in range(x):  # x = 2  range = 0,1  #  x = 3  range = 0,1,2
#         l.append(i*i)   # 0, 1    # [3,2,1,0,1,4]
#     print(l)  # l = [0,1]  # [3,2,1,0,1,4] # [0,1,0,1,4]
#
# f(2)
# f(3,[3,2,1])
# f(3)
# 	输出结果
# 17. 请将 "1,2,3"，变成 ["1","2","3"]
# s = "1,2,3"
# lst = s.split(",")
# print(lst)
# 18. is和==的区别是？ is 是比较内存地址  == 是比较数值
# 19. 输入一行字符，分别统计出其中英文字母、空格、数字和其它字符的个数。
# s = "asdf 7LKS&65lfdhKB LGN;lg"
# def func(x):
#     print("数字:%s" % len([i for i in x if i.isdigit()]))
#     print("字母:%s" % len([i for i in x if i.isalpha()]))
#     print("空格:%s" % len([i for i in x if i.isspace()]))
#     print("其他:%s" % len([i for i in x if not i.isspace() and not i.isdigit() and not i.isalpha()]))
# func(s)

# s = "123T"
# for i in s:
#     if i.isdigit():
#         print(i)
# res = filter(func,s)
# print(list(res))

# 20. 求1～100间所有偶数的和（亦可奇数和，使用while循环写）
# count = 1
# sum = 0
# while count <= 100:
#     if count % 2 == 0:
#         sum += count
#     count += 1
# print(sum)

# 21. 将列表['alex', 'steven', 'egon'] 中的每一个元素使用 ‘\_’ 连接为一个字符串
# lst = ['alex', 'steven', 'egon']
# s = "_".join(lst)
# print(s)














































# #!/usr/bin/env python3
#
# 1. 列举字典的10种常用方法
# 2. 列举元组的10种常用方法
# 3. 列举集合的10种常用方法
# 4. 判断"yuan"是否在[123,(1,"yuan"),{"yuan":"handsome"},"yuanhao"],如何判断以及对应结果？
# lst = [123,(1,"yuan"),{"yuan":"handsome"},"yuanhao"]
#
# def func(argv):
#     for i in argv:
#         if type(i) == str or type(i) == int:
#             if i == "yuan":
#                 print("找到yuan")
#         else:
#             func(i)
# func(lst)




# # 5.
# i = ['name', 'age']
# l = ['金鑫', 58]
# print(dict([i, l]))
# print(dict([i, l]))
# {“name”:"金鑫","age":18}
# 	请用代码实现结果{“name”:"金鑫","age":18}
# def func(argv):
#     dic = {}
#     dic[argv[0]] = argv[1]
#     return dic
# print(list(map(func,zip(i, l))))


# 6. range和xrange的区别，以及各自的应用场景
# print(dir(range(10)))
# 7.  v1 = {}
# 	v2 = {3:5}
# 	v3 = {[11,23]:5}  # 字典的key必须是可哈希的，可哈希=不可变
# 	v4 = {(11,23):5}
# 	下面代码谁报错？
# 8.将字符串："k:1|k1:2|k2:3|k3:4"，处理成 python 字典：{k:1, k1:2, ... }
# s = "k:1|k1:2|k2:3|k3:4"
# lst = [i.split(":") for i in s.split("|")]
# # print(lst)
# print(dict([*lst]))
#
#
# 9. 有如下变量（tu是个元祖），请实现要求的功能
#     tu = ("alex", [11, 22, {"k1": 'v1', "k2": ["age", "name"], "k3": (11,22,33)}, 44])
#     a. 讲述元祖的特性
#       只读列表
#     b. 请问tu变量中的第一个元素 “alex” 是否可被修改？
#       不可修改
#     c. 请问tu变量中的"k2"对应的值是什么类型？是否可以被修改？如果可以，请在其中添加一个元素 “Seven”
#       列表
# tu = ("alex", [11, 22, {"k1": 'v1', "k2": ["age", "name"], "k3": (11,22,33)}, 44])
# tu[1][2]["k2"].append("Seven")
# print(tu)
# 	d. 请问tu变量中的"k3"对应的值是什么类型？是否可以被修改？如果可以，请在其中添加一个元素 “Seven”
#   元组类型，不可修改
#
# # 10. 字典dic,dic = {'k1': "v1", "k2": "v2", "k3": [11,22,33]}
# dic = {'k1': "v1", "k2": "v2", "k3": [11,22,33]}
# #     a. 请循环输出所有的key
# for i in dic.keys():
#     print(i)
# #     b. 请循环输出所有的value
# for i in dic.values():
#     print(i)
# #     c. 请循环输出所有的key和value
# for k, v in dic.items():
#     print(k, v)
# #     d. 请在字典中添加一个键值对，"k4": "v4"，输出添加后的字典
# dic["k4"] = "v4"
# print(dic)
# #     e. 请在修改字典中 “k1” 对应的值为 “alex”，输出修改后的字典
# dic["k1"] = "alex"
#
# #     f. 请在k3对应的值中追加一个元素 44，输出修改后的字典
# dic["k3"].append(44)
# #     g. 请在k3对应的值的第 1 个位置插入个元素 18，输出修改后的字典
# dic["k3"].insert(1, 18)
# print(dic)
# #
# 11. 元素分类
#     有如下值li= [11,22,33,44,55,66,77,88,99,90]，将所有大于 66 的值保存至字典的第一个key中，将小于 66 的值保存至第二个key的值中。
# # 	即： {'k1': 大于66的所有值列表, 'k2': 小于66的所有值列表}
# li= [11,22,33,44,55,66,77,88,99,90]
# dic = {"k1": [],
#        "k2": []}
# for i in li:
#     if i > 66:
#         dic["k1"].append(i)
#     else:
#         dic["k2"].append(i)
# print(dic)
#
#
# 12. 输出商品列表，用户输入序号，显示用户选中的商品
#     商品 li = ["手机", "电脑", '鼠标垫', '游艇']
# 	要求：1：页面显示 序号 + 商品名称，如：
# 	      	1 手机
# 		   	2 电脑
# 	     		 …
# 	     2： 用户输入选择的商品序号，然后打印商品名称
# 	     3：如果用户输入的商品序号有误，则提示输入有误，并重新输入。
# 	     4：用户输入Q或者q，退出程序。
#
# 13.对字典进行增删改查  {"Development":"开发小哥","OP":"运维小哥","Operate":"运营小仙女","UI":"UI小仙女"}
#
# 14. 写一个三次认证 实现用户输入用户名和密码,当用户名为 seven 或 alex 且 密码为 123 时,显示登陆成功,否则登陆失败,失败时允许重复输入三次
#
# 15. 元祖和列表的区别
#
# 16. 从键盘接收一百分制成绩（0~100），要求输出其对应的成绩等级A~E。其中，90分以上为'A'，80~89分为'B'，70~79分为'C'，60~69分为'D'，60分以下为'E'
#
# 17. 深浅copy-引用和copy(),deepcopy()的区别
#
# 18. 自定义两个，并求交集，合集，差集。
#
#
#
#
#
