# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-16 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20180916_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='title',
            field=models.CharField(max_length=16, verbose_name='权限名称'),
        ),
    ]
