# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-16 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_auto_20180916_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='icon',
            field=models.CharField(default=True, max_length=16, verbose_name='菜单图标'),
        ),
    ]
