# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-16 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_permission_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='icon',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='菜单图标'),
        ),
    ]
