# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20180827_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='phone',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
