# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180813_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='hostname',
            field=models.CharField(max_length=32),
        ),
    ]
