# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-02 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fault_reporting', '0002_auto_20180902_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultreport',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faultreport',
            name='down_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faultreport',
            name='up_count',
            field=models.IntegerField(default=0),
        ),
    ]
